# Generated by Django 4.2.4 on 2023-09-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_banner_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner_area",
            name="Link",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
